version: '3'
services:

  otel-collector:
    container_name: otel-collector
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.83.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
      - ./logs:/logs
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      # - 55679:55679 # zpages extension

  jaeger:
    image: jaegertracing/all-in-one:1.47
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      # - 4317:4317
      # - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - LOG_LEVEL=debug
      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=${PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR}
      - PROMETHEUS_QUERY_NAMESPACE=${PROMETHEUS_QUERY_NAMESPACE}
      - PROMETHEUS_QUERY_DURATION_UNIT=${PROMETHEUS_QUERY_DURATION_UNIT}
    volumes:
      -  "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    container_name: jaeger
    command: --query.ui-config /etc/jaeger/jaeger-ui.json

  kamuri-rest-test:
    container_name: kamuri-rest-test
    build:
      context: ./kamuri-rest-test
      args:
        ARG_JAVA_APP_DIR: /usr/local/my_app
        SERVICE_NAME: kamuri-rest-test
        OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    ports:
      - 8080:8080

  kamuri-rest-connection:
    container_name: kamuri-rest-connection
    build:
      context: ./kamuri-rest-connection
      args:
        ARG_JAVA_APP_DIR: /usr/local/my_app
        SERVICE_NAME: kamuri-rest-connection
        OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    environment:
      APPLICATION_URL: http://kamuri-rest-test:8080
    ports:
      - 8081:8080
